-- ============================================================================
-- WDOS Migration 089 — Nigeria's 774 LGAs + Leadership Hierarchy Visibility
-- (Phase 101)
--
-- Part A: all 774 Nigerian Local Government Areas, fetched and verified
-- against official state-by-state counts before seeding (Kano 44, Bayelsa
-- 8, and every other state's count independently cross-checked to total
-- exactly 774; zero duplicates; sequential 1-774 in the source). Seeded
-- as org_units (level='district_lga') under their real parent state.
-- This is the one honest gap named in Phase 100 — now closed with
-- verified data, not fabricated.
--
-- Part B: "the country lead, state coordinator can still see leadership
-- structure under them in that particular region, message them etc, and
-- they can message back" — exactly like Banana Republic, applied to the
-- real 111 leaders. Two things were missing:
--   1. A leader could only see PEERS at her own seat (My Team, Phase 94)
--      — never the seats BELOW her in the hierarchy. A Country Lead
--      could not see her State Coordinators; a State Coordinator could
--      not see her LGA Coordinators. New: my_subtree().
--   2. Messaging (same_leadership_team, Phase 94) only permitted peers
--      at the SAME seat. Now extended to also permit messaging along
--      the hierarchy — a leader and anyone holding a seat in her own
--      subtree — while leaving the wall exactly as solid as before for
--      everyone else.
-- ============================================================================

-- 1 ▸ seed the 774 LGAs under their real parent state ------------------------
do $$
declare ng_country uuid; r record;
begin
  select id into ng_country from org_units
   where level = 'country' and country_iso = 'NG';
  for r in select * from (values
  ('Aba North', 'Abia'),
  ('Aba South', 'Abia'),
  ('Arochukwu', 'Abia'),
  ('Bende', 'Abia'),
  ('Ikwuano', 'Abia'),
  ('Isiala Ngwa North', 'Abia'),
  ('Isiala Ngwa South', 'Abia'),
  ('Isuikwuato', 'Abia'),
  ('Obi Ngwa', 'Abia'),
  ('Ohafia', 'Abia'),
  ('Osisioma Ngwa', 'Abia'),
  ('Ugwunagbo', 'Abia'),
  ('Ukwa East', 'Abia'),
  ('Ukwa West', 'Abia'),
  ('Umuahia North', 'Abia'),
  ('Umuahia South', 'Abia'),
  ('Umu Nneochi', 'Abia'),
  ('Demsa', 'Adamawa'),
  ('Fufore', 'Adamawa'),
  ('Ganye', 'Adamawa'),
  ('Gayuk', 'Adamawa'),
  ('Gombi', 'Adamawa'),
  ('Grie', 'Adamawa'),
  ('Hong', 'Adamawa'),
  ('Jada', 'Adamawa'),
  ('Lamurde', 'Adamawa'),
  ('Madagali', 'Adamawa'),
  ('Maiha', 'Adamawa'),
  ('Mayo-Belwa', 'Adamawa'),
  ('Michika', 'Adamawa'),
  ('Mubi North', 'Adamawa'),
  ('Mubi South', 'Adamawa'),
  ('Numan', 'Adamawa'),
  ('Shelleng', 'Adamawa'),
  ('Song', 'Adamawa'),
  ('Toungo', 'Adamawa'),
  ('Yola North', 'Adamawa'),
  ('Yola South', 'Adamawa'),
  ('Abak', 'Akwa Ibom'),
  ('Eastern Obolo', 'Akwa Ibom'),
  ('Eket', 'Akwa Ibom'),
  ('Esit Eket', 'Akwa Ibom'),
  ('Essien Udim', 'Akwa Ibom'),
  ('Etim Ekpo', 'Akwa Ibom'),
  ('Etinan', 'Akwa Ibom'),
  ('Ibeno', 'Akwa Ibom'),
  ('Ibesikpo Asutan', 'Akwa Ibom'),
  ('Ibiono-Ibom', 'Akwa Ibom'),
  ('Ika', 'Akwa Ibom'),
  ('Ikono', 'Akwa Ibom'),
  ('Ikot Abasi', 'Akwa Ibom'),
  ('Ikot Ekpene', 'Akwa Ibom'),
  ('Ini', 'Akwa Ibom'),
  ('Itu', 'Akwa Ibom'),
  ('Mbo', 'Akwa Ibom'),
  ('Mkpat-Enin', 'Akwa Ibom'),
  ('Nsit-Atai', 'Akwa Ibom'),
  ('Nsit-Ibom', 'Akwa Ibom'),
  ('Nsit-Ubium', 'Akwa Ibom'),
  ('Obot Akara', 'Akwa Ibom'),
  ('Okobo', 'Akwa Ibom'),
  ('Onna', 'Akwa Ibom'),
  ('Oron', 'Akwa Ibom'),
  ('Oruk Anam', 'Akwa Ibom'),
  ('Udung-Uko', 'Akwa Ibom'),
  ('Ukanafun', 'Akwa Ibom'),
  ('Uruan', 'Akwa Ibom'),
  ('Urue-Offong/Oruko', 'Akwa Ibom'),
  ('Uyo', 'Akwa Ibom'),
  ('Aguata', 'Anambra'),
  ('Anambra East', 'Anambra'),
  ('Anambra West', 'Anambra'),
  ('Anaocha', 'Anambra'),
  ('Awka North', 'Anambra'),
  ('Awka South', 'Anambra'),
  ('Ayamelum', 'Anambra'),
  ('Dunukofia', 'Anambra'),
  ('Ekwusigo', 'Anambra'),
  ('Idemili North', 'Anambra'),
  ('Idemili South', 'Anambra'),
  ('Ihiala', 'Anambra'),
  ('Njikoka', 'Anambra'),
  ('Nnewi North', 'Anambra'),
  ('Nnewi South', 'Anambra'),
  ('Ogbaru', 'Anambra'),
  ('Onitsha North', 'Anambra'),
  ('Onitsha South', 'Anambra'),
  ('Orumba North', 'Anambra'),
  ('Orumba South', 'Anambra'),
  ('Oyi', 'Anambra'),
  ('Alkaleri', 'Bauchi'),
  ('Bauchi', 'Bauchi'),
  ('Bogoro', 'Bauchi'),
  ('Damban', 'Bauchi'),
  ('Darazo', 'Bauchi'),
  ('Dass', 'Bauchi'),
  ('Gamawa', 'Bauchi'),
  ('Ganjuwa', 'Bauchi'),
  ('Giade', 'Bauchi'),
  ('Itas/Gadau', 'Bauchi'),
  ('Jama''are', 'Bauchi'),
  ('Katagum', 'Bauchi'),
  ('Kirfi', 'Bauchi'),
  ('Misau', 'Bauchi'),
  ('Ningi', 'Bauchi'),
  ('Shira', 'Bauchi'),
  ('Tafawa Balewa', 'Bauchi'),
  ('Toro', 'Bauchi'),
  ('Warji', 'Bauchi'),
  ('Zaki', 'Bauchi'),
  ('Brass', 'Bayelsa'),
  ('Ekeremor', 'Bayelsa'),
  ('Kolokuma/Opokuma', 'Bayelsa'),
  ('Nembe', 'Bayelsa'),
  ('Ogbia', 'Bayelsa'),
  ('Sagbama', 'Bayelsa'),
  ('Southern Ijaw', 'Bayelsa'),
  ('Yenagoa', 'Bayelsa'),
  ('Ado', 'Benue'),
  ('Agatu', 'Benue'),
  ('Apa', 'Benue'),
  ('Buruku', 'Benue'),
  ('Gboko', 'Benue'),
  ('Guma', 'Benue'),
  ('Gwer East', 'Benue'),
  ('Gwer West', 'Benue'),
  ('Katsina-Ala', 'Benue'),
  ('Konshisha', 'Benue'),
  ('Kwande', 'Benue'),
  ('Logo', 'Benue'),
  ('Makurdi', 'Benue'),
  ('Obi', 'Benue'),
  ('Ogbadibo', 'Benue'),
  ('Ohimini', 'Benue'),
  ('Oju', 'Benue'),
  ('Okpokwu', 'Benue'),
  ('Otukpo', 'Benue'),
  ('Tarka', 'Benue'),
  ('Ukum', 'Benue'),
  ('Ushongo', 'Benue'),
  ('Vandeikya', 'Benue'),
  ('Abadam', 'Borno'),
  ('Askira/Uba', 'Borno'),
  ('Bama', 'Borno'),
  ('Bayo', 'Borno'),
  ('Biu', 'Borno'),
  ('Chibok', 'Borno'),
  ('Damboa', 'Borno'),
  ('Dikwa', 'Borno'),
  ('Gubio', 'Borno'),
  ('Guzamala', 'Borno'),
  ('Gwoza', 'Borno'),
  ('Hawul', 'Borno'),
  ('Jere', 'Borno'),
  ('Kaga', 'Borno'),
  ('Kala/Balge', 'Borno'),
  ('Konduga', 'Borno'),
  ('Kukawa', 'Borno'),
  ('Kwaya Kusar', 'Borno'),
  ('Mafa', 'Borno'),
  ('Magumeri', 'Borno'),
  ('Maiduguri', 'Borno'),
  ('Marte', 'Borno'),
  ('Mobbar', 'Borno'),
  ('Monguno', 'Borno'),
  ('Ngala', 'Borno'),
  ('Nganzai', 'Borno'),
  ('Shani', 'Borno'),
  ('Abi', 'Cross River'),
  ('Akamkpa', 'Cross River'),
  ('Akpabuyo', 'Cross River'),
  ('Bakassi', 'Cross River'),
  ('Bekwarra', 'Cross River'),
  ('Biase', 'Cross River'),
  ('Boki', 'Cross River'),
  ('Calabar Municipal', 'Cross River'),
  ('Calabar South', 'Cross River'),
  ('Etung', 'Cross River'),
  ('Ikom', 'Cross River'),
  ('Obanliku', 'Cross River'),
  ('Obubra', 'Cross River'),
  ('Obudu', 'Cross River'),
  ('Odukpani', 'Cross River'),
  ('Ogoja', 'Cross River'),
  ('Yakurr', 'Cross River'),
  ('Yala', 'Cross River'),
  ('Aniocha North', 'Delta'),
  ('Aniocha South', 'Delta'),
  ('Bomadi', 'Delta'),
  ('Burutu', 'Delta'),
  ('Ethiope East', 'Delta'),
  ('Ethiope West', 'Delta'),
  ('Ika North East', 'Delta'),
  ('Ika South', 'Delta'),
  ('Isoko North', 'Delta'),
  ('Isoko South', 'Delta'),
  ('Ndokwa East', 'Delta'),
  ('Ndokwa West', 'Delta'),
  ('Okpe', 'Delta'),
  ('Oshimili North', 'Delta'),
  ('Oshimili South', 'Delta'),
  ('Patani', 'Delta'),
  ('Sapele', 'Delta'),
  ('Udu', 'Delta'),
  ('Ughelli North', 'Delta'),
  ('Ughelli South', 'Delta'),
  ('Ukwuani', 'Delta'),
  ('Uvwie', 'Delta'),
  ('Warri North', 'Delta'),
  ('Warri South', 'Delta'),
  ('Warri South West', 'Delta'),
  ('Abakaliki', 'Ebonyi'),
  ('Afikpo North', 'Ebonyi'),
  ('Afikpo South', 'Ebonyi'),
  ('Ebonyi', 'Ebonyi'),
  ('Ezza North', 'Ebonyi'),
  ('Ezza South', 'Ebonyi'),
  ('Ikwo', 'Ebonyi'),
  ('Ishielu', 'Ebonyi'),
  ('Ivo', 'Ebonyi'),
  ('Izzi', 'Ebonyi'),
  ('Ohaozara', 'Ebonyi'),
  ('Ohaukwu', 'Ebonyi'),
  ('Onicha', 'Ebonyi'),
  ('Akoko-Edo', 'Edo'),
  ('Egor', 'Edo'),
  ('Esan Central', 'Edo'),
  ('Esan North-East', 'Edo'),
  ('Esan South-East', 'Edo'),
  ('Esan West', 'Edo'),
  ('Etsako Central', 'Edo'),
  ('Etsako East', 'Edo'),
  ('Etsako West', 'Edo'),
  ('Igueben', 'Edo'),
  ('Ikpoba-Okha', 'Edo'),
  ('Oredo', 'Edo'),
  ('Orhionmwon', 'Edo'),
  ('Ovia North-East', 'Edo'),
  ('Ovia South-West', 'Edo'),
  ('Owan East', 'Edo'),
  ('Owan West', 'Edo'),
  ('Uhunmwonde', 'Edo'),
  ('Ado-Ekiti', 'Ekiti'),
  ('Efon', 'Ekiti'),
  ('Ekiti East', 'Ekiti'),
  ('Ekiti South-West', 'Ekiti'),
  ('Ekiti West', 'Ekiti'),
  ('Emure', 'Ekiti'),
  ('Gbonyin', 'Ekiti'),
  ('Ido-Osi', 'Ekiti'),
  ('Ijero', 'Ekiti'),
  ('Ikere', 'Ekiti'),
  ('Ikole', 'Ekiti'),
  ('Ilejemeje', 'Ekiti'),
  ('Irepodun/Ifelodun', 'Ekiti'),
  ('Ise/Orun', 'Ekiti'),
  ('Moba', 'Ekiti'),
  ('Oye', 'Ekiti'),
  ('Aninri', 'Enugu'),
  ('Awgu', 'Enugu'),
  ('Enugu East', 'Enugu'),
  ('Enugu North', 'Enugu'),
  ('Enugu South', 'Enugu'),
  ('Ezeagu', 'Enugu'),
  ('Igbo-Etiti', 'Enugu'),
  ('Igbo-Eze North', 'Enugu'),
  ('Igbo-Eze South', 'Enugu'),
  ('Isi-Uzo', 'Enugu'),
  ('Nkanu East', 'Enugu'),
  ('Nkanu West', 'Enugu'),
  ('Nsukka', 'Enugu'),
  ('Oji River', 'Enugu'),
  ('Udenu', 'Enugu'),
  ('Udi', 'Enugu'),
  ('Uzo-Uwani', 'Enugu'),
  ('Abaji', 'Federal Capital Territory'),
  ('Bwari', 'Federal Capital Territory'),
  ('Gwagwalada', 'Federal Capital Territory'),
  ('Kuje', 'Federal Capital Territory'),
  ('Kwali', 'Federal Capital Territory'),
  ('Municipal', 'Federal Capital Territory'),
  ('Akko', 'Gombe'),
  ('Balanga', 'Gombe'),
  ('Billiri', 'Gombe'),
  ('Dukku', 'Gombe'),
  ('Funakaye', 'Gombe'),
  ('Gombe', 'Gombe'),
  ('Kaltungo', 'Gombe'),
  ('Kwami', 'Gombe'),
  ('Nafada', 'Gombe'),
  ('Shongom', 'Gombe'),
  ('Yamaltu/Deba', 'Gombe'),
  ('Aboh Mbaise', 'Imo'),
  ('Ahiazu Mbaise', 'Imo'),
  ('Ehime Mbano', 'Imo'),
  ('Ezinihitte Mbaise', 'Imo'),
  ('Ideato North', 'Imo'),
  ('Ideato South', 'Imo'),
  ('Ihitte/Uboma', 'Imo'),
  ('Ikeduru', 'Imo'),
  ('Isiala Mbano', 'Imo'),
  ('Isu', 'Imo'),
  ('Mbaitoli', 'Imo'),
  ('Ngor-Okpala', 'Imo'),
  ('Njaba', 'Imo'),
  ('Nkwerre', 'Imo'),
  ('Nwangele', 'Imo'),
  ('Obowo', 'Imo'),
  ('Oguta', 'Imo'),
  ('Ohaji/Egbema', 'Imo'),
  ('Okigwe', 'Imo'),
  ('Onuimo', 'Imo'),
  ('Orlu', 'Imo'),
  ('Orsu', 'Imo'),
  ('Oru East', 'Imo'),
  ('Oru West', 'Imo'),
  ('Owerri Municipal', 'Imo'),
  ('Owerri North', 'Imo'),
  ('Owerri West', 'Imo'),
  ('Auyo', 'Jigawa'),
  ('Babura', 'Jigawa'),
  ('Biriniwa', 'Jigawa'),
  ('Birnin Kudu', 'Jigawa'),
  ('Buji', 'Jigawa'),
  ('Dutse', 'Jigawa'),
  ('Gagarawa', 'Jigawa'),
  ('Garki', 'Jigawa'),
  ('Gumel', 'Jigawa'),
  ('Guri', 'Jigawa'),
  ('Gwaram', 'Jigawa'),
  ('Gwiwa', 'Jigawa'),
  ('Hadejia', 'Jigawa'),
  ('Jahun', 'Jigawa'),
  ('Kafin Hausa', 'Jigawa'),
  ('Kaugama', 'Jigawa'),
  ('Kazaure', 'Jigawa'),
  ('Kiri Kasama', 'Jigawa'),
  ('Kiyawa', 'Jigawa'),
  ('Maigatari', 'Jigawa'),
  ('Malam Madori', 'Jigawa'),
  ('Miga', 'Jigawa'),
  ('Ringim', 'Jigawa'),
  ('Roni', 'Jigawa'),
  ('Sule Tankarkar', 'Jigawa'),
  ('Taura', 'Jigawa'),
  ('Yankwashi', 'Jigawa'),
  ('Birnin Gwari', 'Kaduna'),
  ('Chikun', 'Kaduna'),
  ('Giwa', 'Kaduna'),
  ('Igabi', 'Kaduna'),
  ('Ikara', 'Kaduna'),
  ('Jaba', 'Kaduna'),
  ('Jema''a', 'Kaduna'),
  ('Kachia', 'Kaduna'),
  ('Kaduna North', 'Kaduna'),
  ('Kaduna South', 'Kaduna'),
  ('Kagarko', 'Kaduna'),
  ('Kajuru', 'Kaduna'),
  ('Kaura', 'Kaduna'),
  ('Kauru', 'Kaduna'),
  ('Kubau', 'Kaduna'),
  ('Kudan', 'Kaduna'),
  ('Lere', 'Kaduna'),
  ('Makarfi', 'Kaduna'),
  ('Sabon Gari', 'Kaduna'),
  ('Sanga', 'Kaduna'),
  ('Soba', 'Kaduna'),
  ('Zangon Kataf', 'Kaduna'),
  ('Zaria', 'Kaduna'),
  ('Ajingi', 'Kano'),
  ('Albasu', 'Kano'),
  ('Bagwai', 'Kano'),
  ('Bebeji', 'Kano'),
  ('Bichi', 'Kano'),
  ('Bunkure', 'Kano'),
  ('Dala', 'Kano'),
  ('Dambatta', 'Kano'),
  ('Dawakin Kudu', 'Kano'),
  ('Dawakin Tofa', 'Kano'),
  ('Doguwa', 'Kano'),
  ('Fagge', 'Kano'),
  ('Gabasawa', 'Kano'),
  ('Garko', 'Kano'),
  ('Garun Mallam', 'Kano'),
  ('Gaya', 'Kano'),
  ('Gezawa', 'Kano'),
  ('Gwale', 'Kano'),
  ('Gwarzo', 'Kano'),
  ('Kabo', 'Kano'),
  ('Kano Municipal', 'Kano'),
  ('Karaye', 'Kano'),
  ('Kibiya', 'Kano'),
  ('Kiru', 'Kano'),
  ('Kumbotso', 'Kano'),
  ('Kunchi', 'Kano'),
  ('Kura', 'Kano'),
  ('Madobi', 'Kano'),
  ('Makoda', 'Kano'),
  ('Minjibir', 'Kano'),
  ('Nassarawa', 'Kano'),
  ('Rano', 'Kano'),
  ('Rimin Gado', 'Kano'),
  ('Rogo', 'Kano'),
  ('Shanono', 'Kano'),
  ('Sumaila', 'Kano'),
  ('Takai', 'Kano'),
  ('Tarauni', 'Kano'),
  ('Tofa', 'Kano'),
  ('Tsanyawa', 'Kano'),
  ('Tudun Wada', 'Kano'),
  ('Ungogo', 'Kano'),
  ('Warawa', 'Kano'),
  ('Wudil', 'Kano'),
  ('Bakori', 'Katsina'),
  ('Batagarawa', 'Katsina'),
  ('Batsari', 'Katsina'),
  ('Baure', 'Katsina'),
  ('Bindawa', 'Katsina'),
  ('Charanchi', 'Katsina'),
  ('Dan Musa', 'Katsina'),
  ('Dandume', 'Katsina'),
  ('Danja', 'Katsina'),
  ('Daura', 'Katsina'),
  ('Dutsi', 'Katsina'),
  ('Dutsin-Ma', 'Katsina'),
  ('Faskari', 'Katsina'),
  ('Funtua', 'Katsina'),
  ('Ingawa', 'Katsina'),
  ('Jibia', 'Katsina'),
  ('Kafur', 'Katsina'),
  ('Kaita', 'Katsina'),
  ('Kankara', 'Katsina'),
  ('Kankia', 'Katsina'),
  ('Katsina', 'Katsina'),
  ('Kurfi', 'Katsina'),
  ('Kusada', 'Katsina'),
  ('Mai''Adua', 'Katsina'),
  ('Malumfashi', 'Katsina'),
  ('Mani', 'Katsina'),
  ('Mashi', 'Katsina'),
  ('Matazu', 'Katsina'),
  ('Musawa', 'Katsina'),
  ('Rimi', 'Katsina'),
  ('Sabuwa', 'Katsina'),
  ('Safana', 'Katsina'),
  ('Sandamu', 'Katsina'),
  ('Zango', 'Katsina'),
  ('Aleiro', 'Kebbi'),
  ('Arewa Dandi', 'Kebbi'),
  ('Argungu', 'Kebbi'),
  ('Augie', 'Kebbi'),
  ('Bagudo', 'Kebbi'),
  ('Birnin Kebbi', 'Kebbi'),
  ('Bunza', 'Kebbi'),
  ('Dandi', 'Kebbi'),
  ('Fakai', 'Kebbi'),
  ('Gwandu', 'Kebbi'),
  ('Jega', 'Kebbi'),
  ('Kalgo', 'Kebbi'),
  ('Koko/Besse', 'Kebbi'),
  ('Maiyama', 'Kebbi'),
  ('Ngaski', 'Kebbi'),
  ('Sakaba', 'Kebbi'),
  ('Shanga', 'Kebbi'),
  ('Suru', 'Kebbi'),
  ('Wasagu/Danko', 'Kebbi'),
  ('Yauri', 'Kebbi'),
  ('Zuru', 'Kebbi'),
  ('Adavi', 'Kogi'),
  ('Ajaokuta', 'Kogi'),
  ('Ankpa', 'Kogi'),
  ('Bassa', 'Kogi'),
  ('Dekina', 'Kogi'),
  ('Ibaji', 'Kogi'),
  ('Idah', 'Kogi'),
  ('Igalamela-Odolu', 'Kogi'),
  ('Ijumu', 'Kogi'),
  ('Kabba/Bunu', 'Kogi'),
  ('Kogi', 'Kogi'),
  ('Lokoja', 'Kogi'),
  ('Mopa-Muro', 'Kogi'),
  ('Ofu', 'Kogi'),
  ('Ogori/Magongo', 'Kogi'),
  ('Okehi', 'Kogi'),
  ('Okene', 'Kogi'),
  ('Olamaboro', 'Kogi'),
  ('Omala', 'Kogi'),
  ('Yagba East', 'Kogi'),
  ('Yagba West', 'Kogi'),
  ('Asa', 'Kwara'),
  ('Baruten', 'Kwara'),
  ('Edu', 'Kwara'),
  ('Ekiti', 'Kwara'),
  ('Ifelodun', 'Kwara'),
  ('Ilorin East', 'Kwara'),
  ('Ilorin South', 'Kwara'),
  ('Ilorin West', 'Kwara'),
  ('Irepodun', 'Kwara'),
  ('Isin', 'Kwara'),
  ('Kaiama', 'Kwara'),
  ('Moro', 'Kwara'),
  ('Offa', 'Kwara'),
  ('Oke Ero', 'Kwara'),
  ('Oyun', 'Kwara'),
  ('Patigi', 'Kwara'),
  ('Agege', 'Lagos'),
  ('Ajeromi-Ifelodun', 'Lagos'),
  ('Alimosho', 'Lagos'),
  ('Amuwo-Odofin', 'Lagos'),
  ('Apapa', 'Lagos'),
  ('Badagry', 'Lagos'),
  ('Epe', 'Lagos'),
  ('Eti-Osa', 'Lagos'),
  ('Ibeju-Lekki', 'Lagos'),
  ('Ifako-Ijaiye', 'Lagos'),
  ('Ikeja', 'Lagos'),
  ('Ikorodu', 'Lagos'),
  ('Kosofe', 'Lagos'),
  ('Lagos Island', 'Lagos'),
  ('Lagos Mainland', 'Lagos'),
  ('Mushin', 'Lagos'),
  ('Ojo', 'Lagos'),
  ('Oshodi-Isolo', 'Lagos'),
  ('Shomolu', 'Lagos'),
  ('Surulere', 'Lagos'),
  ('Akwanga', 'Nasarawa'),
  ('Awe', 'Nasarawa'),
  ('Doma', 'Nasarawa'),
  ('Karu', 'Nasarawa'),
  ('Keana', 'Nasarawa'),
  ('Keffi', 'Nasarawa'),
  ('Kokona', 'Nasarawa'),
  ('Lafia', 'Nasarawa'),
  ('Nasarawa', 'Nasarawa'),
  ('Nasarawa Egon', 'Nasarawa'),
  ('Obi', 'Nasarawa'),
  ('Toto', 'Nasarawa'),
  ('Wamba', 'Nasarawa'),
  ('Agaie', 'Niger'),
  ('Agwara', 'Niger'),
  ('Bida', 'Niger'),
  ('Borgu', 'Niger'),
  ('Bosso', 'Niger'),
  ('Chanchaga', 'Niger'),
  ('Edati', 'Niger'),
  ('Gbako', 'Niger'),
  ('Gurara', 'Niger'),
  ('Katcha', 'Niger'),
  ('Kontagora', 'Niger'),
  ('Lapai', 'Niger'),
  ('Lavun', 'Niger'),
  ('Magama', 'Niger'),
  ('Mariga', 'Niger'),
  ('Mashegu', 'Niger'),
  ('Mokwa', 'Niger'),
  ('Munya', 'Niger'),
  ('Paikoro', 'Niger'),
  ('Rafi', 'Niger'),
  ('Rijau', 'Niger'),
  ('Shiroro', 'Niger'),
  ('Suleja', 'Niger'),
  ('Tafa', 'Niger'),
  ('Wushishi', 'Niger'),
  ('Abeokuta North', 'Ogun'),
  ('Abeokuta South', 'Ogun'),
  ('Ado-Odo/Ota', 'Ogun'),
  ('Egbado North', 'Ogun'),
  ('Egbado South', 'Ogun'),
  ('Ewekoro', 'Ogun'),
  ('Ifo', 'Ogun'),
  ('Ijebu East', 'Ogun'),
  ('Ijebu North', 'Ogun'),
  ('Ijebu North East', 'Ogun'),
  ('Ijebu Ode', 'Ogun'),
  ('Ikenne', 'Ogun'),
  ('Imeko Afon', 'Ogun'),
  ('Ipokia', 'Ogun'),
  ('Obafemi Owode', 'Ogun'),
  ('Odeda', 'Ogun'),
  ('Odogbolu', 'Ogun'),
  ('Ogun Waterside', 'Ogun'),
  ('Remo North', 'Ogun'),
  ('Sagamu', 'Ogun'),
  ('Akoko North-East', 'Ondo'),
  ('Akoko North-West', 'Ondo'),
  ('Akoko South-East', 'Ondo'),
  ('Akoko South-West', 'Ondo'),
  ('Akure North', 'Ondo'),
  ('Akure South', 'Ondo'),
  ('Ese-Odo', 'Ondo'),
  ('Idanre', 'Ondo'),
  ('Ifedore', 'Ondo'),
  ('Ilaje', 'Ondo'),
  ('Ile Oluji/Okeigbo', 'Ondo'),
  ('Irele', 'Ondo'),
  ('Odigbo', 'Ondo'),
  ('Okitipupa', 'Ondo'),
  ('Ondo East', 'Ondo'),
  ('Ondo West', 'Ondo'),
  ('Ose', 'Ondo'),
  ('Owo', 'Ondo'),
  ('Aiyedaade', 'Osun'),
  ('Aiyedire', 'Osun'),
  ('Atakunmosa East', 'Osun'),
  ('Atakunmosa West', 'Osun'),
  ('Boluwaduro', 'Osun'),
  ('Boripe', 'Osun'),
  ('Ede North', 'Osun'),
  ('Ede South', 'Osun'),
  ('Egbedore', 'Osun'),
  ('Ejigbo', 'Osun'),
  ('Ife Central', 'Osun'),
  ('Ife East', 'Osun'),
  ('Ife North', 'Osun'),
  ('Ife South', 'Osun'),
  ('Ifedayo', 'Osun'),
  ('Ifelodun', 'Osun'),
  ('Ila', 'Osun'),
  ('Ilesa East', 'Osun'),
  ('Ilesa West', 'Osun'),
  ('Irepodun', 'Osun'),
  ('Irewole', 'Osun'),
  ('Isokan', 'Osun'),
  ('Iwo', 'Osun'),
  ('Obokun', 'Osun'),
  ('Odo Otin', 'Osun'),
  ('Ola Oluwa', 'Osun'),
  ('Olorunda', 'Osun'),
  ('Oriade', 'Osun'),
  ('Orolu', 'Osun'),
  ('Osogbo', 'Osun'),
  ('Afijio', 'Oyo'),
  ('Akinyele', 'Oyo'),
  ('Atiba', 'Oyo'),
  ('Atisbo', 'Oyo'),
  ('Egbeda', 'Oyo'),
  ('Ibadan North', 'Oyo'),
  ('Ibadan North-East', 'Oyo'),
  ('Ibadan North-West', 'Oyo'),
  ('Ibadan South-East', 'Oyo'),
  ('Ibadan South-West', 'Oyo'),
  ('Ibarapa Central', 'Oyo'),
  ('Ibarapa East', 'Oyo'),
  ('Ibarapa North', 'Oyo'),
  ('Ido', 'Oyo'),
  ('Irepo', 'Oyo'),
  ('Iseyin', 'Oyo'),
  ('Itesiwaju', 'Oyo'),
  ('Iwajowa', 'Oyo'),
  ('Kajola', 'Oyo'),
  ('Lagelu', 'Oyo'),
  ('Ogbomoso North', 'Oyo'),
  ('Ogbomoso South', 'Oyo'),
  ('Ogo Oluwa', 'Oyo'),
  ('Olorunsogo', 'Oyo'),
  ('Oluyole', 'Oyo'),
  ('Ona Ara', 'Oyo'),
  ('Orelope', 'Oyo'),
  ('Ori Ire', 'Oyo'),
  ('Oyo East', 'Oyo'),
  ('Oyo West', 'Oyo'),
  ('Saki East', 'Oyo'),
  ('Saki West', 'Oyo'),
  ('Surulere', 'Oyo'),
  ('Barkin Ladi', 'Plateau'),
  ('Bassa', 'Plateau'),
  ('Bokkos', 'Plateau'),
  ('Jos East', 'Plateau'),
  ('Jos North', 'Plateau'),
  ('Jos South', 'Plateau'),
  ('Kanam', 'Plateau'),
  ('Kanke', 'Plateau'),
  ('Langtang North', 'Plateau'),
  ('Langtang South', 'Plateau'),
  ('Mangu', 'Plateau'),
  ('Mikang', 'Plateau'),
  ('Pankshin', 'Plateau'),
  ('Qua''an Pan', 'Plateau'),
  ('Riyom', 'Plateau'),
  ('Shendam', 'Plateau'),
  ('Wase', 'Plateau'),
  ('Abua/Odual', 'Rivers'),
  ('Ahoada East', 'Rivers'),
  ('Ahoada West', 'Rivers'),
  ('Akuku-Toru', 'Rivers'),
  ('Andoni', 'Rivers'),
  ('Asari-Toru', 'Rivers'),
  ('Bonny', 'Rivers'),
  ('Degema', 'Rivers'),
  ('Eleme', 'Rivers'),
  ('Emohua', 'Rivers'),
  ('Etche', 'Rivers'),
  ('Gokana', 'Rivers'),
  ('Ikwerre', 'Rivers'),
  ('Khana', 'Rivers'),
  ('Obio/Akpor', 'Rivers'),
  ('Ogba/Egbema/Ndoni', 'Rivers'),
  ('Ogu/Bolo', 'Rivers'),
  ('Okrika', 'Rivers'),
  ('Omuma', 'Rivers'),
  ('Opobo/Nkoro', 'Rivers'),
  ('Oyigbo', 'Rivers'),
  ('Port Harcourt', 'Rivers'),
  ('Tai', 'Rivers'),
  ('Binji', 'Sokoto'),
  ('Bodinga', 'Sokoto'),
  ('Dange Shuni', 'Sokoto'),
  ('Gada', 'Sokoto'),
  ('Goronyo', 'Sokoto'),
  ('Gudu', 'Sokoto'),
  ('Gwadabawa', 'Sokoto'),
  ('Illela', 'Sokoto'),
  ('Isa', 'Sokoto'),
  ('Kebbe', 'Sokoto'),
  ('Kware', 'Sokoto'),
  ('Rabah', 'Sokoto'),
  ('Sabon Birni', 'Sokoto'),
  ('Shagari', 'Sokoto'),
  ('Silame', 'Sokoto'),
  ('Sokoto North', 'Sokoto'),
  ('Sokoto South', 'Sokoto'),
  ('Tambuwal', 'Sokoto'),
  ('Tangaza', 'Sokoto'),
  ('Tureta', 'Sokoto'),
  ('Wamako', 'Sokoto'),
  ('Wurno', 'Sokoto'),
  ('Yabo', 'Sokoto'),
  ('Ardo Kola', 'Taraba'),
  ('Bali', 'Taraba'),
  ('Donga', 'Taraba'),
  ('Gashaka', 'Taraba'),
  ('Gassol', 'Taraba'),
  ('Ibi', 'Taraba'),
  ('Jalingo', 'Taraba'),
  ('Karim Lamido', 'Taraba'),
  ('Kumi', 'Taraba'),
  ('Lau', 'Taraba'),
  ('Sardauna', 'Taraba'),
  ('Takum', 'Taraba'),
  ('Ussa', 'Taraba'),
  ('Wukari', 'Taraba'),
  ('Yorro', 'Taraba'),
  ('Zing', 'Taraba'),
  ('Bade', 'Yobe'),
  ('Bursari', 'Yobe'),
  ('Damaturu', 'Yobe'),
  ('Fika', 'Yobe'),
  ('Fune', 'Yobe'),
  ('Geidam', 'Yobe'),
  ('Gujba', 'Yobe'),
  ('Gulani', 'Yobe'),
  ('Jakusko', 'Yobe'),
  ('Karasuwa', 'Yobe'),
  ('Machina', 'Yobe'),
  ('Nangere', 'Yobe'),
  ('Nguru', 'Yobe'),
  ('Potiskum', 'Yobe'),
  ('Tarmuwa', 'Yobe'),
  ('Yunusari', 'Yobe'),
  ('Yusufari', 'Yobe'),
  ('Anka', 'Zamfara'),
  ('Bakura', 'Zamfara'),
  ('Birnin Magaji/Kiyaw', 'Zamfara'),
  ('Bukkuyum', 'Zamfara'),
  ('Bungudu', 'Zamfara'),
  ('Gummi', 'Zamfara'),
  ('Gusau', 'Zamfara'),
  ('Kaura Namoda', 'Zamfara'),
  ('Maradun', 'Zamfara'),
  ('Maru', 'Zamfara'),
  ('Shinkafi', 'Zamfara'),
  ('Talata Mafara', 'Zamfara'),
  ('Tsafe', 'Zamfara'),
  ('Zurmi', 'Zamfara')
  ) as t(lga_name, state_name)
  loop
    if not exists (
      select 1 from org_units ou
       where ou.level = 'district_lga' and ou.name = r.lga_name
         and ou.parent_id = (select id from org_units
                               where parent_id = ng_country
                                 and level = 'state_region'
                                 and name = r.state_name)
    ) then
      insert into org_units (parent_id, level, name, country_iso)
      select id, 'district_lga', r.lga_name, 'NG'
        from org_units
       where parent_id = ng_country and level = 'state_region'
         and name = r.state_name;
    end if;
  end loop;
end $$;

-- 2 ▸ my_subtree(): everyone at or below any seat I hold, vacant or filled --
create or replace function public.my_subtree()
returns jsonb language plpgsql stable
security definer set search_path = public as $$
declare result jsonb;
begin
  if auth.uid() is null then return '[]'::jsonb; end if;

  with recursive my_units as (
    select org_unit_id as id from role_assignments
     where profile_id = auth.uid() and ends_at is null
    union all
    select ou.id from org_units ou
     join my_units mu on ou.parent_id = mu.id
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'org_unit_id', ou.id,
    'level', ou.level,
    'location', ou.name,
    'role', ra.role,
    'holder_id', ra.profile_id,
    'holder_name', hp.first_name || ' ' || hp.last_name,
    'vacant', ra.profile_id is null
  ) order by ou.level, ou.name), '[]'::jsonb)
    into result
  from my_units u
  join org_units ou on ou.id = u.id
  left join lateral (
    select r.profile_id, r.role from role_assignments r
     where r.org_unit_id = ou.id and r.ends_at is null
     limit 1
  ) ra on true
  left join profiles hp on hp.id = ra.profile_id
  where ou.id not in (select org_unit_id from role_assignments
                       where profile_id = auth.uid() and ends_at is null);

  return result;
end;
$$;
revoke execute on function public.my_subtree() from anon;

-- 3 ▸ extend the messaging wall: peers (existing) OR hierarchy (new) -------
create or replace function public.same_leadership_team(a uuid, b uuid)
returns boolean language sql stable
security definer set search_path = public as $$
  select exists (
    select 1 from role_assignments ra1
    join role_assignments ra2 on ra2.org_unit_id = ra1.org_unit_id
     where ra1.profile_id = a and ra1.ends_at is null
       and ra2.profile_id = b and ra2.ends_at is null
       and a <> b
  )
  or exists (
    with recursive a_subtree as (
      select org_unit_id as id from role_assignments
       where profile_id = a and ends_at is null
      union all
      select ou.id from org_units ou
       join a_subtree s on ou.parent_id = s.id
    )
    select 1 from role_assignments rb
     join a_subtree s on s.id = rb.org_unit_id
     where rb.profile_id = b and rb.ends_at is null
  )
  or exists (
    with recursive b_subtree as (
      select org_unit_id as id from role_assignments
       where profile_id = b and ends_at is null
      union all
      select ou.id from org_units ou
       join b_subtree s on ou.parent_id = s.id
    )
    select 1 from role_assignments ra
     join b_subtree s on s.id = ra.org_unit_id
     where ra.profile_id = a and ra.ends_at is null
  );
$$;

insert into public.schema_migrations (version, name)
values (89, 'lga_seed_and_subtree_visibility') on conflict (version) do nothing;
